trigger: none

pool:
  name: 'my-agent-pool'

variables:
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'
  BasePath: 'EasySave-2.0/'
  CLIPath: 'EasySave-1.0/'
  GUIPath: 'EasySaveGUI/'
  CLISolution: '$(BasePath)$(CLIPath)**/*.sln'
  GUISolution: '$(BasePath)$(GUIPath)**/*.sln'
  RestoreBuildProjects: '$(BasePath)$(CLIPath)**/*.csproj;$(BasePath)$(GUIPath)**/*.csproj'
  PublishFolder: '$(Build.ArtifactStagingDirectory)/publish'
  CLIPublishFolder: '$(PublishFolder)/CLI'
  GUIPublishFolder: '$(PublishFolder)/GUI'

name: Release-2.0.$(Build.BuildId)

steps:
- task: UseDotNet@2
  inputs:
    version: '6.x'
    includePreviewVersions: false

# Restauration pour CLI et GUI
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(RestoreBuildProjects)'



# Construction pour la solution CLI
- task: DotNetCoreCLI@2
  displayName: 'Build CLI Solution'
  inputs:
    command: 'build'
    projects: '$(CLISolution)'
    arguments: '--configuration $(BuildConfiguration)'

# Construction pour la solution GUI
- task: DotNetCoreCLI@2
  displayName: 'Build GUI Solution'
  inputs:
    command: 'build'
    projects: '$(GUISolution)'
    arguments: '--configuration $(BuildConfiguration)'

# Tests unitaires
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '$(BasePath)**/UnitTest*/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

# Publication pour CLI
- task: DotNetCoreCLI@2
  displayName: 'Publish CLI Projects'
  inputs:
    command: 'publish'
    projects: '$(CLISolution)'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(CLIPublishFolder)'
    zipAfterPublish: false

# Publication pour GUI
- task: DotNetCoreCLI@2
  displayName: 'Publish GUI Projects'
  inputs:
    command: 'publish'
    projects: '$(GUISolution)'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(GUIPublishFolder)'
    zipAfterPublish: false